name: Build and Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Run TypeScript type-check
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npx eslint 'src/**/*.{js,ts,tsx}'

      - name: Check Content-Security-Policy syntax
        run: |
          grep -R "http-equiv=\"Content-Security-Policy\"" dist/index.html \
            && echo "CSP tag looks good" \
            || (echo "Missing or malformed CSP meta"; exit 1)

      - name: Smoke-test local server
        run: |
          npx serve dist -l 5000 &
          sleep 2
          http_status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/proposal-flow/)
          test "$http_status" = "200"
          http_status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/proposal-flow/dashboard)
          test "$http_status" = "200"

      - name: Create 404.html fallback
        run: cp dist/index.html dist/404.html

      - name: Deploy to gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          npx gh-pages -d dist \
            --repo https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git \
            --branch gh-pages \
            --silent

      - name: Verify live site
        run: |
          sleep 10
          STATUS=$(curl -I -s https://thrare00.github.io/proposal-flow/ | head -n1 | awk '{print $2}')
          test "$STATUS" = "200"
